### ISSUE TITLE
buildpack distribution standard

### ISSUE THREAD

**Issue by michaelshobbs** [heroku/heroku-buildpack-emberjs#5]
Apologies for creating an issue here but wasn't sure of a better forum to ask. Is there any reason this buildpack needs to differ from the rest of the official buildpacks with regards to how it's distributed? 

The majority (all maybe?) of the other buildpacks can be included in an app (either Heroku or dokku, et al) via a GitHub URL. I see here there is a build step that compiles things like your `buildpack.c` from mruby-cli and builds your `tgz` artifact. Other buildpacks pull down dependent binaries from S3 or other sources. Can we not do that here? 

Maybe a better question is, is this the path forward for official Heroku buildpacks or is this just a one-off? Thank you for entertaining my questions. 😄

**Comment by hone** [comment]
First off, this is not an reflection on any other official buildpacks. It's in fact not official, but an open source initiative for running Ember.js on Heroku.

With respect to the compiling, yes you can't include it with a GitHub URL because of the compiling aspect that `mruby-cli` uses. I debated on whether to write it in Ruby, bash, or as its own binary with `mruby-cli`. I decided that being able to compile my own binary and not be dependent on the stack image outweighed this since it's possible point to any `.tgz` file. There's talk about some work to make this easier in the future.

Thanks for your interest and questions. Hopefully that answers everything.

**Comment by michaelshobbs** [comment]
Ah ok. I think the fact that the buildpack resides under the Heroku github org lends more weight (and possibly causes more anxiety) around these particular design decisions and how they could be a glimpse into the future of Heroku buildpacks.

Thanks for clarifying.

**Comment by hone** [comment]
@michaelshobbs was it an issue in making it work with dokku?

**Comment by michaelshobbs** [comment]
Yes. See gliderlabs/herokuish#143 and gliderlabs/herokuish#144 for details. TL:DR we never built in support downloading random urls for use as a buildpack. **shrug**

**Comment by hone** [comment]
@michaelshobbs Thanks for the context and getting it working.
